server:
  port:8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

datasource:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://project-1.cehckoacemxp.ap-northeast-2.rds.amazonaws.com:3306/mydb




jwt:
    secret-key: ${JWT_SECRET_KEY}
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace









